.catalog:
  name: "Alfresco"
  version: "5.1.0-201605-GA"
  description: "Alfresco Electronic Document Management"
  uuid: alfresco-5.1-201605-1
  minimum_rancher_version: v0.56.0
  questions:
    - variable: database_name
      description: "Name of the Alfresco database"
      label: "Database name"
      type: "string"
      required: true
      default: "alfresco"
    - variable: database_user
      description: "Login for the Alfresco database"
      label: "Database login"
      type: "string"
      required: true
      default: "alfresco"
    - variable: database_password
      description: "Password for the Alfresco database"
      label: "Database password"
      type: "string"
      required: true
      default: "alfresco"
    - variable: "volumedriver"
      description: "Choose the Volume Driver being used.(Option: local or rancher-nfs)"
      label: "Volume Driver:"
      required: true
      default: local
      type: "enum"
      options:
        - local
        - rancher-nfs

alfresco:
  scale: 1
  health_check:
    port: 8080
    interval: 5000
    unhealthy_threshold: 3
    strategy: recreate
    healthy_threshold: 3
    response_timeout: 5000

postgres:
  scale: 1
  health_check:
    port: 5432
    interval: 5000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 5000
    healthy_threshold: 3

postgres-storage:
  scale: 1

alfresco-storage:
  scale: 1
